name: note_app_v1
description: A notes application with authentication

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.0
  awesome_notifications: ^0.10.1 # Use the latest version
  intl: ^0.20.0
  logger: ^2.5.0
  permission_handler: ^11.4.0
  syncfusion_flutter_datepicker: ^28.2.11+1 # For date picker
  timezone: ^0.9.1 # For timezone support
  provider: ^6.1.2
  math_expressions: ^2.7.0
  flutter_colorpicker: ^1.1.0
  file_picker: ^9.2.1
  fl_chart: ^0.70.2
  sqflite: ^2.4.2
  path: ^1.9.1
  http: ^1.3.0
  mssql_connection: ^2.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
